# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('orgname', models.CharField(max_length=200)),
                ('orgdesc', models.TextField(max_length=200)),
                ('orgid', models.AutoField(primary_key=True, serialize=False)),
                ('orgusername', models.CharField(max_length=200)),
                ('orgstat', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'In-review')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('postitle', models.CharField(max_length=50)),
                ('posdesc', models.TextField(max_length=200)),
                ('level', models.PositiveIntegerField(choices=[(1, 'Basic'), (2, 'Immediate'), (3, 'Advanced')], default=1)),
                ('posid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectname', models.CharField(max_length=200)),
                ('projdesc', models.CharField(max_length=500)),
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('projstatus', models.BooleanField(default=False)),
                ('orgname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunto.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolname', models.CharField(max_length=200)),
                ('schooladdress', models.CharField(max_length=200)),
                ('schoolid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('volunteerid', models.AutoField(primary_key=True, serialize=False)),
                ('joindate', models.DateTimeField(verbose_name='Join Date')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunto.School')),
            ],
        ),
    ]
