# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='orgpw',
            field=models.CharField(default='', max_length=30),
        ),
    ]
