# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunto', '0002_organization_orgpw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='username',
        ),
    ]
