# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunto', '0004_auto_20171112_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='joindate',
        ),
    ]
