# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunto', '0005_remove_volunteer_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunto.Project'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='volunto.School'),
        ),
    ]
