# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunto', '0006_auto_20171114_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
    ]
