# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunto', '0007_remove_volunteer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicationid', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_firstname', models.CharField(max_length=30)),
                ('applicant_lastname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='orgname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunto.Organization', verbose_name='Project Sponsor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projdesc',
            field=models.CharField(max_length=500, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectname',
            field=models.CharField(max_length=200, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projstatus',
            field=models.BooleanField(default=False, verbose_name='Project Status'),
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunto.Project', verbose_name='Project Name'),
        ),
    ]
