# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunto', '0008_auto_20180103_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_firstname',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_lastname',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
    ]
