# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunto', '0012_auto_20180210_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=None, max_length=30, null=True, unique=True),
        ),
    ]
