# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 09:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunto', '0013_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2234567899'. Only 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
